#!/bin/sh

if [ -z "$1" ]; then
    echo "You must specify a mode"

else
    if [ -z "$2" ]; then
        echo "You must specify a theme name"
    else
        case $1 in
            "backup")
                cp ~/dot_set ~/dotfiles/dot_set
                cp -r ~/.config/awesome ~/dotfiles/$2/
                cp -r ~/.config/picom ~/dotfiles/$2/
                cp -r ~/.local/share/konsole ~/dotfiles/$2/
                cp ~/.xinitrc ~/dotfiles/$2/
                cp ~/.zshrc ~/dotfiles/$2/
                cp -r ~/.poshthemes/mythemes/ ~/dotfiles/$2/poshthemes/
                ;;

            "restore")
                cp -r ~/dotfiles/$2/awesome ~/.config/
                cp -r ~/dotfiles/$2/picom ~/.config/
                cp -r ~/dotfiles/$2/konsole ~/.local/share 
                cp ~/dotfiles/$2/.zshrc ~/.zshrc 
                cp -r ~/dotfiles/$2/poshthemes/mythemes/ ~/.poshthemes
		while true; do
			if [ -z $3 ]; then
				read -p "Copy .xinit?(y/n)" ANS
			else
				if [ "$3" = "--copy-xinitrc" ]; then
					export ANS="y"
				else
					if [ "$3" = "--nocopy-xinitrc" ]; then
						export ANS="n"
					else
						echo $3 "is not a valid argument"
						exit
					fi
				fi
			fi
			case $ANS in
				[Yy]* )
					cp ~/dotfiles/$2/.xinitrc ~/.xinitrc;
					break
				;;

				[Nn]* )
					break
				;;
	
				"")
					cp ~/dotfiles/$2/.xinitrc ~/.xinitrc;
					break
				;;

				*)
					echo "enter a valid choice";
					echo
				;;
			esac
		done

                ;;
        esac
    fi
fi
