# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
# add_newline = true

format = '''$character$directory$git_branch$git_status$all[->](purple) '''
continuation_prompt = "[>>](purple) "

[fill]
symbol =  '-'

[character]    
success_symbol = "[⊙](bold green)"  
error_symbol = "[⊙](bold red)"

[line_break]
disabled = true

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 1
truncate_to_repo = false
truncation_symbol = "../"
style = "blue"

[git_status]
format = "([[(*$conflicted$untracked$modified$staged$renamed$deleted)]($style)($ahead_behind$stashed)]($style)) "
style = "red"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≈"

[git_branch]
format = "[( $branch)]($style)"
style="purple"
# ignore_branches = ["main", "master"]

[cmd_duration]
min_time = 2_000
show_milliseconds = false
disabled = true

[python]
disabled = true

[nodejs]
format = '([$symbol]($style)[$version ]($style italic))'
version_format = "$major.$minor"
symbol = "⬢ "

[dart]
format = '[$symbol($version )]($style)'
version_format = "$major.$minor"
style = "cyan italic"

[gradle]
format = '$symbol[($version )]($style)'
version_format = "$major.$minor"
disabled = true

[java]
format = '$symbol[($version )]($style)'
version_format = "$major"
style = "red italic"

[jobs]
symbol = '+'

[kotlin]
format = '$symbol[($version )]($style)'
symbol = " "
version_format = "$major.$minor"
disabled = true

[rust]
format = '$symbol[($version )]($style)'
version_format = "$major.$minor"
style = "red italic"

#disabled

[status]
disabled = true
format = '$status'

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[buf]
disabled = true

[bun]
disabled = true

[c]
disabled = true

[cmake]
disabled = true

[cobol]
disabled = true

[conda]
disabled = true

[container]
disabled = true

[crystal]
disabled = true

[daml]
disabled = true

[deno]
disabled = true

[docker_context]
disabled = true

[dotnet]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[erlang]
disabled = true

[fennel]
disabled = true

[fossil_branch]
disabled = true

[gcloud]
disabled = true

[git_metrics]
disabled = true

[golang]
disabled = true

[guix_shell]
disabled = true

[haskell]
disabled = true

[haxe]
disabled = true

[helm]
disabled = true

[hostname]
disabled = true

[julia]
disabled = true

[kubernetes]
disabled = true

[lua]
disabled = true

[memory_usage]
disabled = true

[meson]
disabled = true

[hg_branch]
disabled = true

[nim]
disabled = true

[nix_shell]
disabled = true

[ocaml]
disabled = true

[opa]
disabled = true

[openstack]
disabled = true

[os]
disabled = true

[package]
disabled = true

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
disabled = true

[pulumi]
disabled = true

[purescript]
disabled = true

[rlang]
disabled = true

[raku]
disabled = true

[red]
disabled = true

[ruby]
disabled = true

[scala]
disabled = true

[shlvl]
disabled = true

[singularity]
disabled = true

[spack]
disabled = true

[swift]
disabled = true

[terraform]
disabled = true

[time]
disabled = true

[vagrant]
disabled = true

[vlang]
disabled = true

[vcsh]
disabled = true

[zig]
disabled = true